### ISSUE TITLE
User creation error 

### ISSUE THREAD

**Issue by NaysKutzu** [wohahobg/pterosync#42] opened 2024-09-13 19:10 UTC
```php
AH01071: Got error 'PHP message: [WHMCS Application] ERROR: TypeError: Unsupported operand types: int + string in /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/modules/servers/pterosync/helper.php:541 Stack trace: #0 /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/modules/servers/pterosync/pterosync.php(576): pteroSyncProcessAllocations() #1 [internal function]: pterosync_CreateAccount() #2 /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func() #3 /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\\Module\\AbstractModule->call() #4 /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/includes/modulefunctions.php(0): WHMCS\\Module\\Server->call() #5 /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/vendor/whmcs/whmcs-foundation/lib/Service/Service.php(0): ModuleCallFunction() #6 /var/www/vhosts/mythicalsystems...', referer: https://billing.mythicalsystems.xyz/cart.php?a=checkout
--

```

**Comment by wohahobg** [comment] 2024-09-13 19:34
The problem is in your WHMCS. Not in the module

**Comment by NaysKutzu** [comment] 2024-09-14 08:46
wdym in my whmcs?

**Comment by NaysKutzu** [comment] 2024-09-14 08:46
then update the docs i just copy pasted from docs 😂

**Comment by wohahobg** [comment] 2024-09-14 08:50
Well, how I can know what's wrong when details are not being shared  ? 

Share with me your product setup, module log and etc.  Tell me more what you have done to get that error.

**Comment by NaysKutzu** [comment] 2024-09-14 08:52
![image](https://github.com/user-attachments/assets/11f252a2-efff-40bd-89ac-d469420cc7a6)
 
And then if i buy the product i get this error on the server creation: 
```bash
AH01079: Got error 'PHP message: [WHMCS Application] ERROR: TypeError: Unsupported operand types: int + string in /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/modules/servers/pterosync/helper.php:541 Stack trace: #0 /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/modules/servers/pterosync/pterosync.php(576): pteroSyncProcessAllocations() #1 [internal function]: pterosync_CreateAccount() #2 /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func() #3 /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\\Module\\AbstractModule->call() #4 /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/includes/modulefunctions.php(0): WHMCS\\Module\\Server->call() #5 /var/www/vhosts/mythicalsystems.xyz/billing.mythicalsystems.xyz/vendor/whmcs/whmcs-foundation/lib/Service/Service.php(0): ModuleCallFunction() #6 /var/www/vhosts/mythicalsystems...', referer: https://billing.mythicalsystems.xyz/cart.php?a=checkout
```

**Comment by wohahobg** [comment] 2024-09-14 08:59
Please download the main branch and try with that.

**Comment by NaysKutzu** [comment] 2024-09-14 09:00
Sure wait a min

**Comment by NaysKutzu** [comment] 2024-09-14 09:34
Nope

**Comment by wohahobg** [comment] 2024-09-14 09:38
What same error ?

**Comment by NaysKutzu** [comment] 2024-09-14 09:38
Yeah ;(

**Comment by wohahobg** [comment] 2024-09-14 09:55
![image](https://github.com/user-attachments/assets/e0a2d77e-21d9-4482-be8b-59e1d93b108c)
I can see you are not running paid version of WHMCS. Maybe that's the issue. I don't give support for cracked versions.

**Comment by NaysKutzu** [comment] 2024-09-14 10:06
Its not cracked i pay for it 😂 

I got it form a reseller!

**Comment by NaysKutzu** [comment] 2024-09-14 10:08
![image](https://github.com/user-attachments/assets/2b4921d9-cf5d-4564-8ae2-ddbc8d76f1e0)

And the download link from my downloads is: https://releases.whmcs.com/v2/pkgs/whmcs-8.10.1-release.1.zip

**Comment by wohahobg** [comment] 2024-09-14 11:12
In that case. This so wired. I will look into this more.

**Comment by wohahobg** [comment] 2024-09-14 11:35
Ok i was checking with my friend and definitely your not using licensed whmcs. In that case i can't help you. Even if you buy it from reseller whmcs should show that your billing is valid.

So i won't spend hours for searching for an issue for a cracked version. 

Also the module has 0 issues for such as problem on over 200 hostings even more, u r the only one and the only one with not valid whmcs.

Closing this. When you get you valid whmcs please try again.

**Closed as completed by wohahobg** 2024-09-14 11:36 UTC
